# Generated by Django 5.0.5 on 2024-05-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('course_type', models.CharField(max_length=10)),
                ('course_days', models.CharField(max_length=10)),
                ('course_start_time', models.TimeField()),
                ('course_end_time', models.TimeField()),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('course_instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
